"""add scraper registry and foreign-id mapping tables

Revision ID: 0a20320936b2
Revises: 729344285850
Create Date: 2026-07-11 19:06:22.743717

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '0a20320936b2'
down_revision = '729344285850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('folder', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder'),
    sa.UniqueConstraint('name')
    )
    op.create_table('active_scraper_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_scraper_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_scraper_configs_data_type'), ['data_type'], unique=True)

    op.create_table('season_foreign_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_id', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_id', 'foreign_id', name='uix_season_foreign_id_scraper_foreign'),
    sa.UniqueConstraint('scraper_id', 'season_id', name='uix_season_foreign_id_scraper_season')
    )
    with op.batch_alter_table('season_foreign_ids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_foreign_ids_foreign_id'), ['foreign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_season_foreign_ids_scraper_id'), ['scraper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_season_foreign_ids_season_id'), ['season_id'], unique=False)

    op.create_table('team_foreign_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_id', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_id', 'foreign_id', name='uix_team_foreign_id_scraper_foreign'),
    sa.UniqueConstraint('scraper_id', 'team_id', name='uix_team_foreign_id_scraper_team')
    )
    with op.batch_alter_table('team_foreign_ids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_foreign_ids_foreign_id'), ['foreign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_foreign_ids_scraper_id'), ['scraper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_foreign_ids_team_id'), ['team_id'], unique=False)

    op.create_table('league_foreign_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_id', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_id', 'foreign_id', name='uix_league_foreign_id_scraper_foreign'),
    sa.UniqueConstraint('scraper_id', 'league_id', name='uix_league_foreign_id_scraper_league')
    )
    with op.batch_alter_table('league_foreign_ids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_foreign_ids_foreign_id'), ['foreign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_foreign_ids_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_foreign_ids_scraper_id'), ['scraper_id'], unique=False)

    op.create_table('player_foreign_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_id', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_id', 'foreign_id', name='uix_player_foreign_id_scraper_foreign'),
    sa.UniqueConstraint('scraper_id', 'player_id', name='uix_player_foreign_id_scraper_player')
    )
    with op.batch_alter_table('player_foreign_ids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_foreign_ids_foreign_id'), ['foreign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_foreign_ids_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_foreign_ids_scraper_id'), ['scraper_id'], unique=False)

    op.create_table('game_foreign_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_id', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_id', 'foreign_id', name='uix_game_foreign_id_scraper_foreign'),
    sa.UniqueConstraint('scraper_id', 'game_id', name='uix_game_foreign_id_scraper_game')
    )
    with op.batch_alter_table('game_foreign_ids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_foreign_ids_foreign_id'), ['foreign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_foreign_ids_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_foreign_ids_scraper_id'), ['scraper_id'], unique=False)

    # ### data migration: seed scrapery + backfill foreign_id/superscore_name -> mapping tables ###
    scrapers_table = sa.table('scrapers',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('folder', sa.String),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    now = datetime.utcnow()
    op.bulk_insert(scrapers_table, [
        {'name': 'Małopolski ZPN', 'folder': 'malopolskizpn', 'created_at': now, 'updated_at': now},
        {'name': 'Łączy Nas Piłka', 'folder': 'laczynaspilka', 'created_at': now, 'updated_at': now},
        {'name': 'Superscore', 'folder': 'superscore', 'created_at': now, 'updated_at': now},
    ])

    # Aktywne scrapery per typ danych: teams/players -> laczynaspilka (jedyne źródło
    # z realnymi ID), games -> malopolskizpn jako rozsądny domyślny wybór (drugie
    # źródło meczów, superscore, zostaje dostępne do przełączenia przez
    # ActiveScraperConfig.set_active_scraper('game', ...) bez migracji).
    op.execute("""
        INSERT INTO active_scraper_configs (data_type, scraper_id, created_at, updated_at)
        SELECT 'team', (SELECT id FROM scrapers WHERE folder = 'laczynaspilka'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    """)
    op.execute("""
        INSERT INTO active_scraper_configs (data_type, scraper_id, created_at, updated_at)
        SELECT 'player', (SELECT id FROM scrapers WHERE folder = 'laczynaspilka'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    """)
    op.execute("""
        INSERT INTO active_scraper_configs (data_type, scraper_id, created_at, updated_at)
        SELECT 'game', (SELECT id FROM scrapers WHERE folder = 'malopolskizpn'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    """)

    op.execute("""
        INSERT INTO team_foreign_ids (scraper_id, team_id, foreign_id, created_at, updated_at)
        SELECT (SELECT id FROM scrapers WHERE folder = 'laczynaspilka'), id, foreign_id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        FROM teams WHERE foreign_id IS NOT NULL
    """)
    op.execute("""
        INSERT INTO team_foreign_ids (scraper_id, team_id, foreign_id, created_at, updated_at)
        SELECT (SELECT id FROM scrapers WHERE folder = 'superscore'), id, superscore_name, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        FROM teams WHERE superscore_name IS NOT NULL
    """)
    op.execute("""
        INSERT INTO player_foreign_ids (scraper_id, player_id, foreign_id, created_at, updated_at)
        SELECT (SELECT id FROM scrapers WHERE folder = 'laczynaspilka'), id, foreign_id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        FROM players WHERE foreign_id IS NOT NULL
    """)
    # games.foreign_id jest dziś zawsze puste (malopolskizpn/superscore dopasowują
    # mecze po lidze/kolejce/drużynach, nie po ID) — nic do przeniesienia.
    # leagues/seasons.foreign_id też zawsze puste w obu modułach.
    # ### end data migration ###

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('foreign_id')

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('foreign_id')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('foreign_id')

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_column('foreign_id')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('superscore_name')
        batch_op.drop_column('foreign_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foreign_id', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('superscore_name', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foreign_id', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foreign_id', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foreign_id', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foreign_id', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('game_foreign_ids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_foreign_ids_scraper_id'))
        batch_op.drop_index(batch_op.f('ix_game_foreign_ids_game_id'))
        batch_op.drop_index(batch_op.f('ix_game_foreign_ids_foreign_id'))

    op.drop_table('game_foreign_ids')
    with op.batch_alter_table('player_foreign_ids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_foreign_ids_scraper_id'))
        batch_op.drop_index(batch_op.f('ix_player_foreign_ids_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_foreign_ids_foreign_id'))

    op.drop_table('player_foreign_ids')
    with op.batch_alter_table('league_foreign_ids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_foreign_ids_scraper_id'))
        batch_op.drop_index(batch_op.f('ix_league_foreign_ids_league_id'))
        batch_op.drop_index(batch_op.f('ix_league_foreign_ids_foreign_id'))

    op.drop_table('league_foreign_ids')
    with op.batch_alter_table('team_foreign_ids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_foreign_ids_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_foreign_ids_scraper_id'))
        batch_op.drop_index(batch_op.f('ix_team_foreign_ids_foreign_id'))

    op.drop_table('team_foreign_ids')
    with op.batch_alter_table('season_foreign_ids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_foreign_ids_season_id'))
        batch_op.drop_index(batch_op.f('ix_season_foreign_ids_scraper_id'))
        batch_op.drop_index(batch_op.f('ix_season_foreign_ids_foreign_id'))

    op.drop_table('season_foreign_ids')
    with op.batch_alter_table('active_scraper_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_scraper_configs_data_type'))

    op.drop_table('active_scraper_configs')
    op.drop_table('scrapers')
    # ### end Alembic commands ###
