"""add pending_player_matches

Revision ID: 299e5a3ee566
Revises: d683209cc440
Create Date: 2026-07-12 07:04:06.320565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299e5a3ee566'
down_revision = 'd683209cc440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_player_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_first_name', sa.String(length=100), nullable=False),
    sa.Column('scraped_last_name', sa.String(length=100), nullable=False),
    sa.Column('scraped_foreign_id', sa.String(length=500), nullable=False),
    sa.Column('scraped_is_goalkeeper', sa.Boolean(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('suggested_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.ForeignKeyConstraint(['suggested_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_id', 'team_id', 'scraped_foreign_id', name='uix_pending_player_match_scraper_team_foreign')
    )
    with op.batch_alter_table('pending_player_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_player_matches_scraper_id'), ['scraper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_player_matches_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_player_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_player_matches_team_id'))
        batch_op.drop_index(batch_op.f('ix_pending_player_matches_scraper_id'))

    op.drop_table('pending_player_matches')
    # ### end Alembic commands ###
