"""add pending_team_matches

Revision ID: 3ec272b22dec
Revises: 4f3507da9255
Create Date: 2026-07-12 00:40:07.434050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec272b22dec'
down_revision = '4f3507da9255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_team_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_name', sa.String(length=200), nullable=False),
    sa.Column('scraped_foreign_id', sa.String(length=500), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('suggested_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.ForeignKeyConstraint(['suggested_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_id', 'league_id', 'scraped_foreign_id', name='uix_pending_team_match_scraper_league_foreign')
    )
    with op.batch_alter_table('pending_team_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_team_matches_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_team_matches_scraper_id'), ['scraper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_team_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_team_matches_scraper_id'))
        batch_op.drop_index(batch_op.f('ix_pending_team_matches_league_id'))

    op.drop_table('pending_team_matches')
    # ### end Alembic commands ###
