"""initial_baseline

Revision ID: 4179a8851d3f
Revises: 
Create Date: 2026-06-09 02:14:32.702570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4179a8851d3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_images', schema=None) as batch_op:
        batch_op.alter_column('id',
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('id',
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('id',
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('background_images', schema=None) as batch_op:
        batch_op.alter_column('id',
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
