"""add camera_recording_segments and timer_samples

Revision ID: 4d8e2a1f6c9b
Revises: 9c3a7e1d5f2b
Create Date: 2026-07-15 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8e2a1f6c9b'
down_revision = '9c3a7e1d5f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_recording_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorder_camera_id', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('reported_started_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camera_recording_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_recording_segments_ended_at'), ['ended_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_recording_segments_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_recording_segments_period_id'), ['period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_recording_segments_recorder_camera_id'), ['recorder_camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_recording_segments_started_at'), ['started_at'], unique=False)

    op.create_table('timer_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elapsed_time_ms', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timer_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timer_samples_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_timer_samples_period_id'), ['period_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timer_samples_period_id'))
        batch_op.drop_index(batch_op.f('ix_timer_samples_occurred_at'))

    op.drop_table('timer_samples')

    with op.batch_alter_table('camera_recording_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_recording_segments_started_at'))
        batch_op.drop_index(batch_op.f('ix_camera_recording_segments_recorder_camera_id'))
        batch_op.drop_index(batch_op.f('ix_camera_recording_segments_period_id'))
        batch_op.drop_index(batch_op.f('ix_camera_recording_segments_game_id'))
        batch_op.drop_index(batch_op.f('ix_camera_recording_segments_ended_at'))

    op.drop_table('camera_recording_segments')

    # ### end Alembic commands ###
