"""Add helper_squad_proposals table

Revision ID: 5c6564d618fc
Revises: 3b7e9f2a1c4d
Create Date: 2026-08-18 02:41:17.861839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6564d618fc'
down_revision = '3b7e9f2a1c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helper_squad_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=True),
    sa.Column('remote_squad_push_id', sa.Integer(), nullable=False),
    sa.Column('coach_name', sa.String(length=100), nullable=True),
    sa.Column('players_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['helper_id'], ['helpers.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helper_squad_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_helper_squad_proposals_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helper_squad_proposals_remote_squad_push_id'), ['remote_squad_push_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_helper_squad_proposals_team_id'), ['team_id'], unique=False)
    # ### end Alembic commands ###
    # Reszta drift-u wykryta przez autogenerate (game_conflicts, indeksy na
    # helper_event_*/helpers) usunięta ręcznie — niepowiązana z tą migracją,
    # nie chcemy jej cicho aplikować przy okazji.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helper_squad_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helper_squad_proposals_team_id'))
        batch_op.drop_index(batch_op.f('ix_helper_squad_proposals_remote_squad_push_id'))
        batch_op.drop_index(batch_op.f('ix_helper_squad_proposals_game_id'))

    op.drop_table('helper_squad_proposals')
    # ### end Alembic commands ###
