"""add laczynaspilka_season_id to leagues

Revision ID: 7a1f2c9e4b6d
Revises: 1b4d65d13bbc
Create Date: 2026-07-15 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1f2c9e4b6d'
down_revision = '1b4d65d13bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laczynaspilka_season_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('laczynaspilka_season_id')

    # ### end Alembic commands ###
