"""add_zone_scheme_to_camera_positions

Revision ID: b41c0ea78311
Revises: fa92dcc79f85
Create Date: 2026-06-09 05:17:05.949899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41c0ea78311'
down_revision = 'fa92dcc79f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium_camera_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_scheme', sa.String(length=20), server_default='FIELD_GRID', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium_camera_positions', schema=None) as batch_op:
        batch_op.drop_column('zone_scheme')

    # ### end Alembic commands ###
