"""add scraped_short_name to pending_team_matches

Revision ID: d683209cc440
Revises: 3ec272b22dec
Create Date: 2026-07-12 00:50:42.578179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd683209cc440'
down_revision = '3ec272b22dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_team_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scraped_short_name', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_team_matches', schema=None) as batch_op:
        batch_op.drop_column('scraped_short_name')

    # ### end Alembic commands ###
