"""add pending_player_departures and nullable players.team_id

Revision ID: e8b80eb38bd1
Revises: 299e5a3ee566
Create Date: 2026-07-12 07:27:49.728768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b80eb38bd1'
down_revision = '299e5a3ee566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_player_departures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_id', 'team_id', 'player_id', name='uix_pending_player_departure_scraper_team_player')
    )
    with op.batch_alter_table('pending_player_departures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_player_departures_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_player_departures_scraper_id'), ['scraper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_player_departures_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               nullable=False)

    with op.batch_alter_table('pending_player_departures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_player_departures_team_id'))
        batch_op.drop_index(batch_op.f('ix_pending_player_departures_scraper_id'))
        batch_op.drop_index(batch_op.f('ix_pending_player_departures_player_id'))

    op.drop_table('pending_player_departures')
    # ### end Alembic commands ###
