"""add_camera_position_code

Revision ID: fa92dcc79f85
Revises: 12861d840007
Create Date: 2026-06-09 05:04:10.030065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa92dcc79f85'
down_revision = '12861d840007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium_camera_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=3), nullable=True))
        batch_op.create_unique_constraint('uix_stadium_camera_position_code', ['stadium_id', 'code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium_camera_positions', schema=None) as batch_op:
        batch_op.drop_constraint('uix_stadium_camera_position_code', type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
