"""add_zone_scheme_to_camera_positions

Revision ID: 2c4ddb9ba4db
Revises: fcfdce6220bb
Create Date: 2026-06-09 05:16:41.660770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4ddb9ba4db'
down_revision = 'fcfdce6220bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium_camera_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_scheme', sa.String(length=20), server_default='FIELD_GRID', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium_camera_positions', schema=None) as batch_op:
        batch_op.drop_column('zone_scheme')

    # ### end Alembic commands ###
