"""add_cam_head_and_camera_extensions

Revision ID: 4b75bb298856
Revises: 2c4ddb9ba4db
Create Date: 2026-06-11 02:16:43.250204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b75bb298856'
down_revision = '2c4ddb9ba4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cam_heads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('head_id')
    )
    with op.batch_alter_table('camera_position_calibrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uix_calibration_position_zone'), type_='unique')
        batch_op.create_index(batch_op.f('ix_camera_position_calibrations_camera_id'), ['camera_id'], unique=False)
        batch_op.create_unique_constraint('uix_calibration_position_camera_zone', ['position_id', 'camera_id', 'zone_code'])

    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cam_head_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gopro_ssid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gopro_password', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uix_camera_cam_head_id', ['cam_head_id'])

    with op.batch_alter_table('game_cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('stadium_camera_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_camera_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium_camera_positions', schema=None) as batch_op:
        batch_op.drop_column('default_camera_id')

    with op.batch_alter_table('game_cameras', schema=None) as batch_op:
        batch_op.drop_column('position_id')

    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_constraint('uix_camera_cam_head_id', type_='unique')
        batch_op.drop_column('gopro_password')
        batch_op.drop_column('gopro_ssid')
        batch_op.drop_column('cam_head_id')

    with op.batch_alter_table('camera_position_calibrations', schema=None) as batch_op:
        batch_op.drop_constraint('uix_calibration_position_camera_zone', type_='unique')
        batch_op.drop_index(batch_op.f('ix_camera_position_calibrations_camera_id'))
        batch_op.create_unique_constraint(batch_op.f('uix_calibration_position_zone'), ['position_id', 'zone_code'])
        batch_op.drop_column('camera_id')

    op.drop_table('cam_heads')
    # ### end Alembic commands ###
