"""initial_baseline

Revision ID: 678b9c41ff82
Revises: 
Create Date: 2026-06-09 02:08:58.815834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678b9c41ff82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_images', schema=None) as batch_op:
        batch_op.alter_column('id',
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('id',
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('event_cameras', schema=None) as batch_op:
        batch_op.alter_column('replay_start_time',
               nullable=False)

    with op.batch_alter_table('game_cameras', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_game_location'), type_='unique')
        batch_op.create_unique_constraint('unique_game_hdmi_input', ['game_id', 'hdmi_input'])

    with op.batch_alter_table('game_players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_player_game'), type_='unique')
        batch_op.create_unique_constraint('unique_game_player', ['player_id', 'game_id'])

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.alter_column('games_url',
               nullable=True)
        batch_op.alter_column('scorers_url',
               nullable=True)
        batch_op.alter_column('assists_url',
               nullable=True)
        batch_op.alter_column('canadian_url',
               nullable=True)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('team_url',
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('team_url',
               nullable=False)

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.alter_column('canadian_url',
               nullable=False)
        batch_op.alter_column('assists_url',
               nullable=False)
        batch_op.alter_column('scorers_url',
               nullable=False)
        batch_op.alter_column('games_url',
               nullable=False)

    with op.batch_alter_table('game_players', schema=None) as batch_op:
        batch_op.drop_constraint('unique_game_player', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_player_game'), ['player_id', 'game_id'])

    with op.batch_alter_table('game_cameras', schema=None) as batch_op:
        batch_op.drop_constraint('unique_game_hdmi_input', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_game_location'), ['game_id', 'location'])

    with op.batch_alter_table('event_cameras', schema=None) as batch_op:
        batch_op.alter_column('replay_start_time',
               nullable=True)

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('id',
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('background_images', schema=None) as batch_op:
        batch_op.alter_column('id',
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
