"""add_zone_scheme_and_rename_cell_code

Revision ID: 7f27531f45e4
Revises: 678b9c41ff82
Create Date: 2026-06-09 03:00:28.932240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f27531f45e4'
down_revision = '678b9c41ff82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera_position_calibrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_code', sa.String(length=30), nullable=False))
        batch_op.drop_constraint(batch_op.f('uix_calibration_position_cell'), type_='unique')
        batch_op.create_unique_constraint('uix_calibration_position_zone', ['position_id', 'zone_code'])
        batch_op.drop_column('cell_code')

    with op.batch_alter_table('stadiums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_scheme', sa.String(length=20), server_default='FIELD_GRID', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadiums', schema=None) as batch_op:
        batch_op.drop_column('zone_scheme')

    with op.batch_alter_table('camera_position_calibrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cell_code', sa.VARCHAR(length=3), nullable=False))
        batch_op.drop_constraint('uix_calibration_position_zone', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_calibration_position_cell'), ['position_id', 'cell_code'])
        batch_op.drop_column('zone_code')

    # ### end Alembic commands ###
