"""add league_scraper_urls, drop flat league url columns

Revision ID: 8cf6bdecdc66
Revises: 9f7897807222
Create Date: 2026-07-11 20:24:32.401839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf6bdecdc66'
down_revision = '9f7897807222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_scraper_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_id', 'league_id', 'url_type', name='uix_league_scraper_url_scraper_league_type')
    )
    with op.batch_alter_table('league_scraper_urls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_scraper_urls_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_scraper_urls_scraper_id'), ['scraper_id'], unique=False)

    # ### data migration: backfill flat URL columns -> league_scraper_urls (scraper nalffutsal) ###
    for url_type in ('games_url', 'table_url', 'scorers_url', 'assists_url', 'canadian_url'):
        op.execute(f"""
            INSERT INTO league_scraper_urls (scraper_id, league_id, url_type, url, created_at, updated_at)
            SELECT (SELECT id FROM scrapers WHERE folder = 'nalffutsal'), id, '{url_type}', {url_type}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
            FROM leagues WHERE {url_type} IS NOT NULL AND {url_type} != ''
        """)
    # ### end data migration ###

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('scorers_url')
        batch_op.drop_column('assists_url')
        batch_op.drop_column('canadian_url')
        batch_op.drop_column('table_url')
        batch_op.drop_column('games_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('table_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('canadian_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('assists_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('scorers_url', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('league_scraper_urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_scraper_urls_scraper_id'))
        batch_op.drop_index(batch_op.f('ix_league_scraper_urls_league_id'))

    op.drop_table('league_scraper_urls')
    # ### end Alembic commands ###
