"""add game_scraper_snapshots and game_conflicts

Revision ID: 9f33df1437a4
Revises: 6767fafc135d
Create Date: 2026-07-14 01:42:57.151594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f33df1437a4'
down_revision = '6767fafc135d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraper_a_home_goals', sa.Integer(), nullable=True),
    sa.Column('scraper_a_away_goals', sa.Integer(), nullable=True),
    sa.Column('scraper_a_home_ht_goals', sa.Integer(), nullable=True),
    sa.Column('scraper_a_away_ht_goals', sa.Integer(), nullable=True),
    sa.Column('scraper_a_date', sa.DateTime(), nullable=True),
    sa.Column('scraper_b_home_goals', sa.Integer(), nullable=True),
    sa.Column('scraper_b_away_goals', sa.Integer(), nullable=True),
    sa.Column('scraper_b_home_ht_goals', sa.Integer(), nullable=True),
    sa.Column('scraper_b_away_ht_goals', sa.Integer(), nullable=True),
    sa.Column('scraper_b_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('scraper_a_id', sa.Integer(), nullable=False),
    sa.Column('scraper_b_id', sa.Integer(), nullable=False),
    sa.Column('resolved_scraper_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['resolved_scraper_id'], ['scrapers.id'], ),
    sa.ForeignKeyConstraint(['scraper_a_id'], ['scrapers.id'], ),
    sa.ForeignKeyConstraint(['scraper_b_id'], ['scrapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_conflicts_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_conflicts_league_id'), ['league_id'], unique=False)

    op.create_table('game_scraper_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team_goals', sa.Integer(), nullable=True),
    sa.Column('away_team_goals', sa.Integer(), nullable=True),
    sa.Column('home_ht_goals', sa.Integer(), nullable=True),
    sa.Column('away_ht_goals', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scraper_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraper_id', 'game_id', name='uix_game_scraper_snapshot_scraper_game')
    )
    with op.batch_alter_table('game_scraper_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_scraper_snapshots_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_scraper_snapshots_scraper_id'), ['scraper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_scraper_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_scraper_snapshots_scraper_id'))
        batch_op.drop_index(batch_op.f('ix_game_scraper_snapshots_game_id'))

    op.drop_table('game_scraper_snapshots')
    with op.batch_alter_table('game_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_conflicts_league_id'))
        batch_op.drop_index(batch_op.f('ix_game_conflicts_game_id'))

    op.drop_table('game_conflicts')
    # ### end Alembic commands ###
