"""add scraped_short_name to pending_team_matches

Revision ID: c07cb583a5f6
Revises: 7c98256758f9
Create Date: 2026-07-12 00:50:59.636452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07cb583a5f6'
down_revision = '7c98256758f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_team_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scraped_short_name', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_team_matches', schema=None) as batch_op:
        batch_op.drop_column('scraped_short_name')

    # ### end Alembic commands ###
