function renderScoreboard(){
    const scoreboardContainer = document.getElementById('scoreboard-container');
    const mainScoreboardContainer = document.createElement('div');
    mainScoreboardContainer.id = 'main-scoreboard-container';
    mainScoreboardContainer.classList.add('scoreboard-row');
    const homeTeamBox = document.createElement('div');
    homeTeamBox.id = 'home-team-box';
    homeTeamBox.classList.add('team-box', 'position-relative');
    const homeTeamUniform = document.createElement('div');
    homeTeamUniform.id = 'home-team-uniform';
    homeTeamUniform.classList.add('team-uniform', 'home-team-uniform', 'both-side-tilted', 'position-relative');
    const homeTeamShortname = document.createElement('div');
    homeTeamShortname.id = 'home-team-shortname';
    homeTeamShortname.classList.add('team-name', 'home-team-shortname', 'position-relative');
    homeTeamBox.appendChild(homeTeamUniform);
    homeTeamBox.appendChild(homeTeamShortname);
    mainScoreboardContainer.appendChild(homeTeamBox);
    const homeTeamScore = document.createElement('div');
    homeTeamScore.id = 'home-team-score';
    homeTeamScore.classList.add('team-score', 'home-team-score', 'both-side-tilted', 'position-relative');
    mainScoreboardContainer.appendChild(homeTeamScore);
    const spaceElement = document.createElement('div');
    spaceElement.id = 'scoreboard-space';
    spaceElement.classList.add('scoreboard-space', 'position-relative');
    mainScoreboardContainer.appendChild(spaceElement);
    const awayTeamScore = document.createElement('div');
    awayTeamScore.id = 'away-team-score';
    awayTeamScore.classList.add('team-score', 'away-team-score', 'both-side-tilted', 'position-relative');
    mainScoreboardContainer.appendChild(awayTeamScore);
    const awayTeamBox = document.createElement('div');
    awayTeamBox.id = 'away-team-box';
    awayTeamBox.classList.add('team-box', 'position-relative');
    const awayTeamUniform = document.createElement('div');
    awayTeamUniform.id = 'away-team-uniform';
    awayTeamUniform.classList.add('team-uniform', 'away-team-uniform', 'both-side-tilted', 'position-relative');
    const awayTeamShortname = document.createElement('div');
    awayTeamShortname.id = 'away-team-shortname';
    awayTeamShortname.classList.add('team-name', 'away-team-shortname', 'position-relative');
    awayTeamBox.appendChild(awayTeamShortname);
    awayTeamBox.appendChild(awayTeamUniform);
    mainScoreboardContainer.appendChild(awayTeamBox);
    const timerDisplay = document.createElement('div');
    timerDisplay.id = 'main-timer-display';
    timerDisplay.classList.add('main-timer-display', 'position-relative');
    mainScoreboardContainer.appendChild(timerDisplay);
    const addedTimeDisplay = document.createElement('div');
    addedTimeDisplay.id = 'added-time-display';
    addedTimeDisplay.classList.add('added-time-display', 'position-absolute');
    const addedTimeLabel = document.createElement('div');
    addedTimeLabel.id = 'added-time-label';
    addedTimeLabel.classList.add('added-time-label');
    addedTimeLabel.innerText = `+5'`;
    addedTimeDisplay.appendChild(addedTimeLabel);
    mainScoreboardContainer.appendChild(addedTimeDisplay);
    const redCardsContainer = document.createElement('div');
    redCardsContainer.id = 'red-cards-container';
    redCardsContainer.classList.add('red-cards-container', 'position-absolute');
    const homeTeamRedCards = document.createElement('div');
    homeTeamRedCards.id = 'home-team-red-cards';
    homeTeamRedCards.classList.add('team-red-cards', 'position-absolute');
    redCardsContainer.appendChild(homeTeamRedCards);
    const awayTeamRedCards = document.createElement('div');
    awayTeamRedCards.id = 'away-team-red-cards';
    awayTeamRedCards.classList.add('team-red-cards', 'position-absolute');
    redCardsContainer.appendChild(awayTeamRedCards);
    scoreboardContainer.appendChild(redCardsContainer);
    scoreboardContainer.appendChild(mainScoreboardContainer);

}

renderScoreboard();